### ISSUE TITLE
goto_position, takeoff, last_uav_position fonksiyonları çalışmamakta

### ISSUE THREAD

**Issue by kadirozgun** [teknofest-suruiha/suruiha_sample_team#2]
Örnek olarak verdiğiniz sample team içerisinde zephyr_controller içinde bulunan  fonksiyonlarımızı keyboard controller üzerinde kullanmaya çalıştığımızda fonksiyonları çağırmakta ama çalışmamakta. Acaba bununla ilgili açıklama yapabilir misiniz? Çünkü onları örnek alarak ilerletmeye çalışsakta çalıştırmakta problem yaşıyoruz.

**Comment by okanasik** [comment]
Merhaba @kadirozgunn, son değişikliklerden sonra hala sorun yaşıyor musunuz? Eğer sorununuz çözüldüyse bu sorunu kapatacağım. Kolaylıklar.

**Comment by kadirozgun** [comment]
Evet calismakta. Konuyu kapatmayi unutmusum kusura bakmayin. Iyi gunler dilerim.
